apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: supermarket
type: Opaque
data:
  root-password: cm9vdF9zZWNyZXQ=   # base64("root_secret")
  username: bWt0                    # base64("mkt")
  password: bWt0X3NlY3JldA==        # base64("mkt_secret")
